version: "3.5"
networks:
  default:
    name: "geb-testing-workshop"
services:
  host-exposed-frontend:
    image: gebish/react-mobx-realworld-example-app:v3
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_ROOT=http://localhost:8080
  frontend:
    image: gebish/react-mobx-realworld-example-app:v3
    environment:
      - REACT_APP_API_ROOT=http://api:8080
  api:
    image: gebish/spring-boot-realworld-example-app:v1
    ports:
      - "8080:8080"