name: CI

on:
  push:
    branches:
      - master
      - solutions

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser:
          - firefox
          - chrome

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11.x
      - name: build
        run: echo TODO run tests on ${{ matrix.browser }}
