name: CI

on:
  push:
    branches:
      - master
      - solutions

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11.x
      - name: start containers
        run: docker-compose up -d
      - name: build
        run: ./gradlew clean testInDocker
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: test-report
          path: build/reports/tests/testInDocker
